services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      - default
      - proxy
    environment:
      - PUID=1000
      - PGID=2000
      - TZ=America/Montreal
      - VERSION=docker
      - UMASK=002
      - ADVERTISE_IP=http://plex.edge.home.lab:80/
    volumes:
      - /home/nama/config/plex:/config
      - /mnt/data/streaming/media:/data/media
    ports:
      - 32400:32400
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.plex.rule=Host(`plex.edge.home.lab`)
      - traefik.http.routers.plex.entrypoints=web
      - traefik.http.routers.plex.middlewares=security-headers@file
      - traefik.http.services.plex.loadbalancer.server.port=32400

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Montreal
    ports:
      - 5055:5055
    volumes:
      - /home/nama/config/overseerr:/app/config
    restart: unless-stopped
    networks: [default, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.overseerr.rule=Host(`overseerr.edge.home.lab`)
      - traefik.http.routers.overseerr.entrypoints=web
      - traefik.http.routers.overseerr.middlewares=security-headers@file
      - traefik.http.services.overseerr.loadbalancer.server.port=5055

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=2000
      - TZ=America/Montreal
      - AUTO_UPDATE=true
      - UMASK=002
    volumes:
      - /home/nama/config/jackett:/config
      - /mnt/data/streaming:/data
    ports:
      - 9117:9117
    restart: unless-stopped
    networks: [default, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jackett.rule=Host(`jackett.edge.home.lab`)
      - traefik.http.routers.jackett.entrypoints=web
      - traefik.http.routers.jackett.middlewares=security-headers@file
      - traefik.http.services.jackett.loadbalancer.server.port=9117

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/Montreal
    ports:
      - 8191:8191
    restart: unless-stopped
    networks: [default, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.edge.home.lab`)
      - traefik.http.routers.flaresolverr.entrypoints=web
      - traefik.http.routers.flaresolverr.middlewares=security-headers@file
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8191

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=2000
      - TZ=America/Montreal
      - UMASK=002
    volumes:
      - /home/nama/config/radarr:/config
      - /mnt/data/streaming:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks: [default, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.radarr.rule=Host(`radarr.edge.home.lab`)
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.middlewares=security-headers@file
      - traefik.http.services.radarr.loadbalancer.server.port=7878

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=2000
      - TZ=America/Montreal
      - UMASK=002
    volumes:
      - /home/nama/config/sonarr:/config
      - /mnt/data/streaming:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks: [default, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.sonarr.rule=Host(`sonarr.edge.home.lab`)
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.routers.sonarr.middlewares=security-headers@file
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Bahamas
      - TZ=America/Montreal
      - FIREWALL=on
      - FIREWALL_INPUT_PORTS=8080
      - DOT=off
      - LOCAL_NETWORK=192.168.2.0/24
      - UPDATER_PERIOD=24h
    restart: unless-stopped
    networks: [default, proxy]
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.edge.home.lab`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.routers.qbittorrent.middlewares=security-headers@file
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=2000
      - TZ=America/Montreal
      - WEBUI_PORT=8080
      - UMASK=002
    volumes:
      - /home/nama/config/qbittorrent:/config
      - /mnt/data/streaming:/data
    restart: unless-stopped

networks:
  proxy:
    external: true
