services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    networks:
      - proxy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Static & dynamic config (local VM paths)
      - /opt/edge/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/edge/traefik/dynamic:/etc/traefik/dynamic:ro

      # Runtime data
      - /opt/edge/traefik/acme:/acme
      - /opt/edge/traefik/logs:/var/log/traefik

    environment:
      - TZ=America/Montreal

    env_file:
       - /opt/edge/traefik/cf.env

    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  proxy:
    external: true
