services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 8000:8000  # To use Edge Agents
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.portainer.rule=Host(`portainer.edge.home.lab`)
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.middlewares=security-headers@file
      - traefik.http.services.portainer.loadbalancer.server.port=9000

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network
  proxy:
    external: true
